export const SCREENING_SETS = {
  SET_1: [
    { id: 's1q1', text: 'Over the past two weeks, how often have you felt little interest or pleasure in daily activities?' },
    { id: 's1q2', text: 'How often have you felt nervous, anxious, or on edge?' },
    { id: 's1q3', text: 'Have you experienced trouble sleeping or changes in eating habits?' },
    { id: 's1q4', text: 'How often do academic pressures feel overwhelming?' },
    { id: 's1q5', text: 'Have you had thoughts about harming yourself or feeling hopeless?' },
    { id: 's1q6', text: 'Do you find it difficult to focus on your studies?' },
    { id: 's1q7', text: 'How often do you feel restless or unable to sit still?' },
    { id: 's1q8', text: 'Do you experience repetitive, unwanted thoughts or feel driven to repeat actions?' },
    { id: 's1q9', text: 'Have you been bullied or faced social exclusion recently?' },
    { id: 's1q10', text: 'Do you frequently feel lonely or isolated?' },
    { id: 's1q11', text: 'Are you comfortable talking to someone when upset?' },
    { id: 's1q12', text: 'Do you experience physical symptoms like headaches or stomachaches during stress?' },
    { id: 's1q13', text: 'Have you noticed any changes in appetite or weight?' },
    { id: 's1q14', text: 'How often do you feel easily irritated or angry?' },
    { id: 's1q15', text: 'Have you used substances like alcohol or drugs to cope with stress?' },
  ],
  SET_2: [
    { id: 's2q1', text: 'How often do feelings of sadness or depression interfere with your daily life?' },
    { id: 's2q2', text: 'Have you been feeling anxious without clear reasons?' },
    { id: 's2q3', text: 'Are you getting enough restful sleep regularly?' },
    { id: 's2q4', text: 'What coping strategies do you use when stressed about schoolwork?' },
    { id: 's2q5', text: 'Have thoughts of self-harm increased or decreased since the last screening?' },
    { id: 's2q6', text: 'How frequently do you struggle to stay attentive during classes?' },
    { id: 's2q7', text: 'Are impulsive behaviors affecting your relationships or school performance?' },
    { id: 's2q8', text: 'How often do compulsions or rituals take up your time?' },
    { id: 's2q9', text: 'Has the experience of bullying or social difficulties changed?' },
    { id: 's2q10', text: 'Do you feel more connected or more isolated socially?' },
    { id: 's2q11', text: 'How confident are you in seeking help for emotional problems?' },
    { id: 's2q12', text: 'Do physical symptoms worsen with emotional stress?' },
    { id: 's2q13', text: 'Have you made changes to your diet or eating patterns recently?' },
    { id: 's2q14', text: 'How do you manage feelings of anger or frustration?' },
    { id: 's2q15', text: 'Are you aware of the effects of substance use on your mental health?' },
  ],
  SET_3: [
    { id: 's3q1', text: "Can you identify specific triggers for mood changes you've experienced?" },
    { id: 's3q2', text: 'How do anxiety symptoms impact your academic and social activities?' },
    { id: 's3q3', text: 'Describe your sleep quality and how it affects your daily functioning.' },
    { id: 's3q4', text: 'What improvements or challenges have you experienced with stress management?' },
    { id: 's3q5', text: 'Describe any recurring suicidal thoughts or urges and their frequency.' },
    { id: 's3q6', text: 'How effective are your concentration and memory during demanding tasks?' },
    { id: 's3q7', text: 'How do hyperactivity or restlessness manifest in your typical day?' },
    { id: 's3q8', text: 'Describe the impact of obsessive thoughts or compulsive behaviors on your life.' },
    { id: 's3q9', text: 'How supported do you feel by peers and adults regarding social issues you face?' },
    { id: 's3q10', text: 'What resources or relationships help decrease your feelings of isolation?' },
    { id: 's3q11', text: 'How proactive are you in seeking mental health support and guidance?' },
    { id: 's3q12', text: 'Have you noticed physical health concerns related to ongoing stress or emotions?' },
    { id: 's3q13', text: 'In what ways have your eating habits adapted to your emotional state?' },
    { id: 's3q14', text: 'How do you express and regulate intense emotions?' },
    { id: 's3q15', text: 'Describe your awareness and actions regarding substance use and its effects.' },
  ],
  SET_4: [
    { id: 's4q1', text: "Reflect on your overall mood in the past few months—what patterns have you noticed?" },
    { id: 's4q2', text: 'How do persistent anxiety symptoms influence your decision-making and behavior?' },
    { id: 's4q3', text: 'Evaluate your sleep patterns over the past months and its correlation with stress.' },
    { id: 's4q4', text: 'What long-term strategies have you developed to handle academic and social stress?' },
    { id: 's4q5', text: 'Describe any progression or reduction in suicidal ideation and emotional distress.' },
    { id: 's4q6', text: 'How consistent is your ability to maintain focus and academic engagement?' },
    { id: 's4q7', text: 'How do you accommodate or manage symptoms related to hyperactivity?' },
    { id: 's4q8', text: 'Analyze changes in obsessive-compulsive behaviors and your management of them.' },
    { id: 's4q9', text: 'How has your social support network evolved, and what impact does it have?' },
    { id: 's4q10', text: 'Discuss your experience with feelings of loneliness and connection over the year.' },
    { id: 's4q11', text: 'Reflect on your journey with professional help or counseling and its outcomes.' },
    { id: 's4q12', text: 'Detail physical health trends connected to your emotional and mental state.' },
    { id: 's4q13', text: 'Summarize how your nutrition and eating patterns relate to your mental health.' },
    { id: 's4q14', text: 'Explain your techniques for emotional regulation and conflict resolution.' },
    { id: 's4q15', text: 'Share an overview of your relationship with substances and any support' },
  ],
};

export const ANSWER_OPTIONS = [
  { value: 0, label: 'Not at all' },
  { value: 1, label: 'Several days' },
  { value: 2, label: 'More than half the days' },
  { value: 3, label: 'Nearly every day' },
];
